site_name: "Onyx"
pages:
  - "doc":
    - "What does Onyx offer?": "user-guide/what-does-it-offer.md"
    - "Concepts": "user-guide/concepts.md"
    - "Onyx's Architecture and Low Level Design": "user-guide/architecture-low-level-design.md"
    - "APIs": "user-guide/apis.md"
    - "Functions": "user-guide/functions.md"
    - "Flow Conditions": "user-guide/flow-conditions.md"
    - "Lifecycles": "user-guide/lifecycles.md"
    - "Deployment": "user-guide/deployment.md"
    - "Environment": "user-guide/environment.md"
    - "Peer Configuration": "user-guide/peer-config.md"
    - "Information Model": "user-guide/information-model.md"
    - "Scheduling Jobs and Tasks": "user-guide/scheduling.md"
    - "Event Subscription": "user-guide/subscription.md"
    - "Plugins": "user-guide/plugins.md"
    - "core.async Internal Plugin": "user-guide/core-async-plugin.md"
    - "Logging": "user-guide/logging.md"
    - "Performance Tuning": "user-guide/performance-tuning.md"
    - "Examples": "user-guide/examples.md"
    - "Frequently Asked Questions": "user-guide/faq.md"
